name: 'k-releaser'
description: 'Automate releases for Rust monorepos with unified versioning'
author: 'Stefan Hausotte'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  command:
    description: 'The k-releaser command to run: release-pr, release, publish, or update'
    required: true
  manifest-path:
    description: 'Path to the Cargo.toml file'
    required: false
    default: 'Cargo.toml'
  config-path:
    description: 'Path to the k-releaser configuration file (if not in Cargo.toml)'
    required: false
  registry:
    description: 'The cargo registry to use'
    required: false
  git-token:
    description: 'The GitHub token to use for creating PRs and releases. If not provided, uses the GITHUB_TOKEN from the environment.'
    required: false
  backend:
    description: 'The git backend to use (github, gitlab, gitea)'
    required: false
    default: 'github'
  output:
    description: 'Output format. When set to "json", prints structured output. Leave empty for normal output.'
    required: false
  dry-run:
    description: 'If true, perform a dry run without making any changes'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Get latest k-releaser version
      id: version
      shell: bash
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/secana/k-releaser/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        echo "version=${LATEST_RELEASE}" >> $GITHUB_OUTPUT
        echo "Latest k-releaser version: ${LATEST_RELEASE}"

    - name: Cache k-releaser binary
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.k-releaser/bin
        key: k-releaser-${{ steps.version.outputs.version }}-${{ runner.os }}-${{ runner.arch }}

    - name: Download k-releaser
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        echo "Downloading k-releaser version ${VERSION}"

        # Create directory for cached binary
        mkdir -p ~/.k-releaser/bin

        # Download and extract binary
        curl -fsSL "https://github.com/secana/k-releaser/releases/download/v${VERSION}/k-releaser-${VERSION}-x86_64-linux-musl.tar.gz" -o k-releaser.tar.gz
        tar -xzf k-releaser.tar.gz
        chmod +x k-releaser
        mv k-releaser ~/.k-releaser/bin/k-releaser
        rm k-releaser.tar.gz

    - name: Install k-releaser
      shell: bash
      run: |
        sudo cp ~/.k-releaser/bin/k-releaser /usr/local/bin/k-releaser
        k-releaser --version

    - name: Run k-releaser
      shell: bash
      run: |
        # Set GITHUB_TOKEN if git-token input is provided
        if [ -n "${{ inputs.git-token }}" ]; then
          export GITHUB_TOKEN="${{ inputs.git-token }}"
        fi

        ARGS=(
          "${{ inputs.command }}"
          "--manifest-path=${{ inputs.manifest-path }}"
        )

        if [ -n "${{ inputs.config-path }}" ]; then
          ARGS+=("--config=${{ inputs.config-path }}")
        fi

        # Only add --registry for publish command
        if [ -n "${{ inputs.registry }}" ] && [[ "${{ inputs.command }}" == "publish" ]]; then
          ARGS+=("--registry=${{ inputs.registry }}")
        fi

        # Only add --forge for commands that support it (release-pr, release)
        if [ -n "${{ inputs.backend }}" ] && [[ "${{ inputs.command }}" == "release-pr" || "${{ inputs.command }}" == "release" ]]; then
          ARGS+=("--forge=${{ inputs.backend }}")
        fi

        # Only add --output for commands that support it (release-pr, release, publish)
        if [ -n "${{ inputs.output }}" ] && [[ "${{ inputs.command }}" != "update" ]]; then
          ARGS+=("--output=${{ inputs.output }}")
        fi

        # Add git-token as explicit argument for commands that support it
        if [ -n "${{ inputs.git-token }}" ] && [[ "${{ inputs.command }}" == "release-pr" || "${{ inputs.command }}" == "release" ]]; then
          ARGS+=("--git-token=${{ inputs.git-token }}")
        fi

        # Add dry-run flag for commands that support it (release-pr, release, publish)
        if [ "${{ inputs.dry-run }}" = "true" ] && [[ "${{ inputs.command }}" != "update" ]]; then
          ARGS+=("--dry-run")
        fi

        ARGS+=("--verbose")

        k-releaser "${ARGS[@]}"
